/**
 * Generates sources-data.ts files by extracting // BEGIN id ... // END id
 * sections from each registry file and embedding them as string literals.
 * Run before building the showcase bundles.
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const showcaseDir = resolve(__dirname, '../src/showcase')

function extractSources(srcPath) {
  const text = readFileSync(srcPath, 'utf8')
  const out = {}
  const re = /\/\/ BEGIN (\w+)\n([\s\S]*?)\/\/ END \1/g
  let m
  while ((m = re.exec(text)) !== null) {
    out[m[1]] = m[2].trim()
  }
  return out
}

function generateFile(sources, outPath) {
  const entries = Object.entries(sources)
    .map(([id, src]) => `  ${id}: ${JSON.stringify(src)}`)
    .join(',\n')
  const content = `// Auto-generated by scripts/gen-sources.mjs — do not edit manually.\nexport const sources: Record<string, string> = {\n${entries},\n}\n`
  writeFileSync(outPath, content, 'utf8')
  console.log(`  Written ${outPath} (${entries.split('\n').length} entries)`)
}

generateFile(
  extractSources(resolve(showcaseDir, 'registry.tsx')),
  resolve(showcaseDir, 'cyber-sources-data.ts')
)
generateFile(
  extractSources(resolve(showcaseDir, 'primary-registry.tsx')),
  resolve(showcaseDir, 'primary-sources-data.ts')
)
console.log('Done.')
